version: "3"

services:
  app:
    build: .
    volumes:
      - app:/home/app
      - "~/.ssh:/home/app/.ssh"
      - "~/.aws:/home/app/.aws"
      - "~/.gitconfig:/home/app/.gitconfig"
      - "~/.gitignore:/home/app/.gitignore"
      - ".:/app"
    working_dir: /app
    environment:
      ERL_AFLAGS: "-kernel shell_history enabled"
      APP_NAME: auth0_ex
      VERSION: 0.0.0-dev
      MIX_BUILD_ROOT: /home/app/_build
      MIX_DEPS_PATH: /home/app/deps
    tty: true
    stdin_open: true
    depends_on:
      - redis

  redis:
    image: public.ecr.aws/bitnami/redis:5.0
    ports:
      - "6379:6379"
    hostname: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  app:
