# Remember to move this to the proper folder

# This workflow allows you to run a `mix hex.retire` for your library

on:
  workflow_dispatch:
    inputs:
      reason:
        description: Retire reason
        required: true
        default: invalid
        type: choice
        options:
          - renamed
          - deprecated
          - security
          - invalid
          - other
      message:
        description: Retire message
        required: true
        default: Version has a breaking bug
        type: string
      version:
        description: Version to retire
        required: true
        default: x.y.z
        type: string

jobs:
  retire:
    runs-on: ubuntu-latest
    env:
      MESSAGE: 
      REASON: 
      VERSION: 
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          elixir-version: '1.15'
      - run: echo "Attempting to retire version $VERSION"
      - run: mix hex.config api_key "$HEX_AUTH_KEY"
        env:
          HEX_AUTH_KEY: 
      - run: mix hex.user whoami
      - run: mix hex.retire prima_auth0_ex "$VERSION" "$REASON" --message "$MESSAGE"
