Hammox.defmock(AuthorizationServiceMock, for: Auth0Ex.TokenProvider.AuthorizationService)
Hammox.defmock(JwksKidsFetcherMock, for: Auth0Ex.TokenProvider.JwksKidsFetcher)
Hammox.defmock(RefreshStrategyMock, for: Auth0Ex.TokenProvider.RefreshStrategy)
Hammox.defmock(TokenCacheMock, for: Auth0Ex.TokenProvider.TokenCache)
Hammox.defmock(TokenServiceMock, for: Auth0Ex.TokenProvider.TokenService)
