Hammox.defmock(AuthorizationServiceMock, for: PrimaAuth0Ex.TokenProvider.AuthorizationService)
Hammox.defmock(JwksKidsFetcherMock, for: PrimaAuth0Ex.TokenProvider.JwksKidsFetcher)
Hammox.defmock(RefreshStrategyMock, for: PrimaAuth0Ex.TokenProvider.RefreshStrategy)
Hammox.defmock(TokenCacheMock, for: PrimaAuth0Ex.TokenCache)
Hammox.defmock(TokenServiceMock, for: PrimaAuth0Ex.TokenProvider.TokenService)
